# Generated by Django 5.2.3 on 2025-06-25 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='interests',
            field=models.TextField(blank=True, help_text='Comma-separated list of interests', null=True),
        ),
    ]
